services:

  cm-mcp:
    build: .
    container_name: cm-mcp
    env_file:
      - .env
    environment:
      # PostgreSQL connection string
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    networks:
      - net_mcp
    ports:
      - 8000:800
    depends_on:
      postgres:
        condition: service_healthy
  
  redis:
    container_name: mcp_redis
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379"
    command: >
      --maxmemory 1024mb
      --maxmemory-policy allkeys-lru
      --maxmemory-samples 5
    networks:
      - net_mcp
    restart: always
  postgres:
    image: postgres:17-alpine
    container_name: his-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-his-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-his_password}
      POSTGRES_DB: ${POSTGRES_DB:-his_db}
      PGDATA: /var/lib/postgresql/data/pgdata
  
    networks:
      - net_mcp
    volumes:
      - postgres-data:/var/lib/postgresql/data 
      - ./2026-01-07_hisinone_edu6.backup:/tmp/backup.backup
      #- ./restore-backup.sh:/tmp/restore-backup.sh 
    ports:
      - "${POSTGRES_PORT_EXTERNAL:-5455}:5432"  
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
  
    
#   pgadmin-his:
#     # https://docs.docker.com/guides/pgadmin/  
#     image: dpage/pgadmin4:latest
#     ports:
#       - 5051:80
#     environment:
#       # Required by pgAdmin
#       PGADMIN_DEFAULT_EMAIL: "adminhistest@his.com"
#       PGADMIN_DEFAULT_PASSWORD: "passwordhistest"
#     networks:
#       - net_his
#     restart: always
   
volumes:
  postgres-data:
  redis-data:

networks:
  net_mcp:
    driver: bridge


# run this inside the postgres container to restore the db  pg_restore --clean --if-exists --no-owner --no-privileges --user ${POSTGRES_USER} --dbname ${POSTGRES_DB} /tmp/backup.backup    
